### ISSUE TITLE
Mod causes random damage tick

### ISSUE THREAD

**Issue by SextupleTap** [DimensionalDevelopment/VanillaFix#29]
In survival mode, you randomly take damage for no reason at all while sprint jumping... The damage tick(ing) occurs while sprint jumping without falling from 3 or more blocks, and when these random damage ticks kill you, the death message is the fall damage death message.

This random damage ticking only happens while walking, sprinting, or sprint jumping, the random damage ticking has even cause game crashes before once the player dies from anything other than /kill, the crashing only happened in one world, the rest of my worlds you just die and nothing more happens.

Here is a video demonstration of the glitch happening in VanillaFix-1.0.4-35:

https://www.youtube.com/watch?v=GRcoXFyctLg&feature=youtu.be

(Note: The glitch DOES occur even when the mod is on its own, I did test the mod 100% by itself and it is causing this problem, and this also happens on any type of block)

**Comment by Janitor53** [comment]
That happens with me too, and once I died from fall damage after teleporting using Journey map with full hp before teleporting.

**Comment by Gbergz** [comment]
I played my own modpack for a few hours, and i was taking random damage sprinting & jumping around. Didn't know what was causing it until i googled it. This is very annoying, i hope this gets resolved.

**Comment by Buttcrackofthunder** [comment]
Same here, I was wondering what causes this.

it seems to happen when you sprint jump for a bit, but then, after a little while, all jumps cause 2-3 hearts of damage.

my theory is that something is screwing with the way the game detects ground contact while calculating fall damage and it isn't registering the times you touch the ground during sprint jumping, but still applies the damage anyway.

**Comment by Runemoro** [comment]
This is fixed in the [latest dev build](https://github.com/DimensionalDevelopment/VanillaFix/releases/latest), and will also be fixed in the next CurseForge release.

**Comment by SextupleTap** [comment]
This issue needs to be re-opened as the glitch was not fixed, fall distance still does not reset properly:

New video:
https://www.youtube.com/watch?v=5agBLG7TJu4&feature=youtu.be

VanillaFix version:
VanillaFix-1.0.5-43.jar

Pack:
Custom Pack

MC Version: 
1.12.2

Tested Mod Independently:
Yes

**Comment by Mattabase** [comment]
This issue still appear to be happening.

VanillaFix version:
VanillaFix-1.0.6-43.jar

Minecraft Forge:
14.23.4.2705

https://goo.gl/iLJxgW
Also my bad on the frame rate. You can see I take damage at one point from just running and jumping. 

This clip shows it happening and this is with just VanillaFix installed.
