### ISSUE TITLE
Default setting for S:scheduledTaskExceptionAction=WARNING_SCREEN, which crashes servers

### ISSUE THREAD

**Issue by JaSpr** [DimensionalDevelopment/VanillaFix#51]
When running VanillaFix on the server, it will occasionally cause a crash due to trying to load a GUI on the server (the welcome screen). 

VanillaFix tried to show a GUI on the server, got `java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen`

[Full crash log](https://gist.github.com/JaSpr/8719ee3ba3221fe6e3947330f563ef74)

## Possible Solution

Either 
A) the default setting should be LOG, or 
B) the mod should check which side it is on (client/server) before attempting to show a GUI (and preferably fall back to another method)

**Comment by Runemoro** [comment]
This was already fixed in 1.0.6.

**Comment by JaSpr** [comment]
Thanks

**Comment by nullKomplex** [comment]
Still happens in 1.0.8-88.jar, even with the #64 NOTIFICATION setting. Crash log is nearly identical, but here it is anyway:

https://gist.github.com/nullKomplex/39399f1189814807d41863aefa2e3544

This is on the same server. Not sure why the format of the crash log differs so greatly though...

This was caused by installing the latest vanilla fix (previous version was before NOTIFICATION was added) and asking a user to get in a bed to see if the previous BedPatch crash was fixed. When they entered the bed this crash occurred. I changed the setting from NOTIFICATION to LOG and it stopped.

**Comment by ZombieHDGaming** [comment]
@nullKomplex Well, firstly, the player doesn't need BedPatch anymore since we've made a fix so it is no longer needed. As for the crash with the notification option, that's to be expected since it can't display a notification. It's a small error on our end that'll be fixed for that in the next version, but just try to keep it on the LOG option for now.

**Comment by Runemoro** [comment]
@nullKomplex It is impossible for there to be a crash with that stack trace using the latest VanillaFix. Do you maybe have two vanillafix jars (1.0.8-88 and an older version) in your mods folder? If not, then this is being caused by another coremod.

**Comment by nullKomplex** [comment]
You can check coremods in the crash report. I also don't think we add any coremods not part of ATM3 that even access GuiScreen other than VanillaFix. Also no, we don't have more than one version, wouldn't that likely crash all the time instead of specifically on a certain config setting only?

That being said, after half a dozen crashes this morning because we accidentally ran the default config for a bit, we can confidently state that it is indeed VanillaFix with the default setting of notification causing this crash. Again, the crashes look identical so I won't post new reports.

**Comment by ZombieHDGaming** [comment]
@nullKomplex Just because I want to test something, can you see if [this build](https://github.com/DimensionalDevelopment/VanillaFix/files/2112144/VanillaFix-1.0.9-SNAPSHOT.jar.zip) works on the server with the notification option? I think this *might* fix it, but it's just to test a theory atm.

**Comment by nullKomplex** [comment]
Well, I was trying to update my client and then start it, both of which take years, and it crashed before I could, with no players even online. Yes that was with that build.

**Comment by ZombieHDGaming** [comment]
@nullKomplex With the same error? That's rather odd.......thanks for testing though. Rune and I are still trying to figure out a good way to fix this.
