### ISSUE TITLE
Fall damage with Galacticraft's Hydraulic platform

### ISSUE THREAD

**Issue by Jacky10X** [DimensionalDevelopment/VanillaFix#52]
it seem it is so buggy for some mod like Galacticraft's Hydraulic platform.
if you try to use this platform to get up or get down
The falling system will treat you as falling and give you damage.
It is work fine if you running the server without vanillafix
i think it also maybe incompatible with other mods.
So is there any option that we can disable the falling damage fix

**Comment by Rongmario** [comment]
This seems to happen when I nerd pole too, when I pole up some blocks aren't registered and I get double fall damage or some sort?

**Comment by ZombieHDGaming** [comment]
@Jacky10X We'll see about maybe adding a config, but for now, can you use [this build](https://github.com/DimensionalDevelopment/VanillaFix/releases/tag/untagged-cc0853c14e29df9a5424) and see if you still take damage? We've done some more fixing to the system to make it a little better, and if it is still there, please let us know and we'll fix some more things. As for incompatibilities with other mods, we haven't heard of any issues thus far, only damage issues with running and jumping so far.

@Rongmario I'll do some testing with nerd poling to see if the latest code base experiences this issue, cause I think we *may* have already fixed this by accident when changing one bit of code.

**Comment by Jacky10X** [comment]
@ZombieHDGaming i found this bug while i am using VanillaFix-1.0.7-68 version So i can sure it still take damage even if you using VanillaFix-1.0.7-68 version

**Comment by ZombieHDGaming** [comment]
@Jacky10X What exactly does the Galacticraft Hydraulic platform do? Cause unless it is a new block or machine, I've never heard of it before

**Comment by Jacky10X** [comment]
@ZombieHDGaming It is elevator, you can move up(press jump) and move down(press sneak), not just teleport. (Actually you can really move up and down) 
maybe this can explain it better:
https://wiki.micdoodle8.com/wiki/Hydraulic_Platform

**Comment by ZombieHDGaming** [comment]
@Jacky10X I haven't tested with Galacticraft just yet, but I have a feeling that Micdoodle may be doing some janky stuff to make the platform work. I did some testing with the RFTools elevator (Ik it's not the same, but hear me out), it seems that works with no issue even though I had thought it would cause damage. I'll do testing with Galacticraft next, but I have a feeling that Micdoodle may need to change the way he handles the movement for the platform.

**Comment by Jacky10X** [comment]
@ZombieHDGaming Forgot to say also this mod also cause the mekanism teleporter also weird
the player will teleport to the teleporter below( it will cause the player suffocated the wall) 
i can confirm it is also vanillafix problem because when we are not using this mod
It is work fine

**Comment by Runemoro** [comment]
Fixed in latest version. I disabled anti-cheat features until I have some more time to properly implement those.

**Comment by Jacky10X** [comment]
@Runemoro 
I just tested it and it is still get damaged when you get up or get down  
i am using Vanillafix-1.0.8-74 version
the problem still has not fixed and it make worse
Sometimes when you get up and you may suddenly fall down to the lower floor

**Comment by Runemoro** [comment]
@Jacky10X Could you upload your debug.log file? This is probably an issue with Galacticraft which VanillaFix triggers by disabling anticheat, and no longer checking that movements are valid.

**Comment by Jacky10X** [comment]
[debug.log](https://github.com/DimensionalDevelopment/VanillaFix/files/2065351/debug.log)
[latest.log](https://github.com/DimensionalDevelopment/VanillaFix/files/2065352/latest.log)
Here it is, Hope you can fix these problem

Also, there is a little glitch but it won't effect the gameplay 
it seem when you use mekanism teleporter 
it will spam the player move into a block
(it is still work fine nothing effect but maybe you can check it and test to make it smoother?
[when you teleport the player will inside the teleporter block and then it will correct you back to the teleporter block above(right position)])

**Comment by Jacky10X** [comment]
@ZombieHDGaming 
Just found out it is really similar to these issues
https://github.com/DimensionalDevelopment/VanillaFix/issues/44
https://github.com/DimensionalDevelopment/VanillaFix/issues/32
https://github.com/DimensionalDevelopment/VanillaFix/issues/29
